P2022-173 Create outer layout
intive/patronage22_poznan_mobile pull request #12
Opened 2022-02-13 15:54 UTC by Bombozaur666

2022-02-14 08:18 UTC, taurelas requested changes

2022-02-14 08:18 UTC, taurelas commented on app/src/main/res/layout/activity_main_screen.xml
> +<?xml version="1.0" encoding="utf-8"?>
why are you creating a new layout? why is not attached to the activity?

2022-02-22 12:53 UTC, taurelas approved these changes

2022-02-22 12:53 UTC, kosiara approved these changes

2022-02-23 17:30 UTC, merged