P2022-1327/MainActivity fragment navigation.
intive/patronage22_poznan_mobile pull request #35
Opened 2022-03-11 14:55 UTC by Lucas-Fresko

Adds 3 fragments to MainActivity and navigation between them using tablayout.

Moves temporary navigation to Details Activity to Home fragment.

2022-03-11 17:19 UTC, taurelas requested changes

2022-03-11 17:19 UTC, taurelas commented on app/src/main/java/com/intive/patronage22/intivi/Adapter/MainFragmentsAdapter.kt
> +                Log.d("bayraktar", "Adapter calls home")
please remove the log messages, we don't want to be targeted by a drone :)

2022-03-11 17:19 UTC, taurelas commented on app/src/main/java/com/intive/patronage22/intivi/Adapter/MainFragmentsAdapter.kt
> +                Log.d("bayraktar", "Adapter calls favourites")
log to be removed

2022-03-11 19:16 UTC, Lucas-Fresko commented on app/src/main/java/com/intive/patronage22/intivi/MainActivity.kt
> +        val adapter = MainFragmentsAdapter(this, tabLayout.tabCount)
I did that before, but it complained with some error so I left it... strangely it's not complaining this time. Code is such a fickle thing.

2022-03-11 19:19 UTC, Lucas-Fresko commented on app/src/main/res/layout/fragment_home.xml
> +        android:layout_marginTop="12dp"
We have decided to stop putting everything into dimens but we can discuss this again during the next meeting.

2022-03-13 12:18 UTC, kosiara commented on app/src/main/java/com/intive/patronage22/intivi/Fragments/FavouritesFragment.kt
> +
avoid double empty lines

2022-03-13 12:18 UTC, merged