P2022 698/create login activity
intive/patronage22_poznan_mobile pull request #4
Opened 2022-02-04 20:06 UTC by Lucas-Fresko

Creates LoginActivity with a header which appears on app launch.

2022-02-04 20:08 UTC, Lucas-Fresko commented
There are 2 minor formatting discrepancies in the manifest file.

2022-02-05 04:38 UTC, taurelas requested changes

2022-02-05 04:38 UTC, taurelas commented on app/src/main/res/layout/activity_login.xml
> +      android:layout_height="48dp"
could you please extract this value to a "login_header_size" resource ?
you can either 
- try and move the cursor on the "48dp" and press option + enter (or ALT+ENtER on Windows I THINK) and choose extract dimension resource
- or manually create the `dimens.xml` in `res/values` and add the relevant tag

Here are examples and a bit more info: https://developer.android.com/guide/topics/resources/more-resources#Dimension

2022-02-05 04:38 UTC, taurelas commented on app/src/main/res/layout/activity_login.xml
> +      android:layout_marginTop="24dp"
same story here, choose appropriate name and add a resource for this dimension

2022-02-05 04:38 UTC, taurelas commented on app/src/main/res/layout/activity_login.xml
> +        android:layout_height="48dp"
are you trying to say that the height of this textview should MATCH the encompassing layout? If so, there is a better way to do it.

2022-02-05 04:38 UTC, taurelas commented on app/src/main/res/layout/activity_login.xml
> +        android:textSize="24sp" />
again, same story with dimens, let's extract this value.

2022-02-05 11:25 UTC, Lucas-Fresko commented on app/src/main/res/layout/activity_login.xml
> +        android:layout_height="48dp"
That wasn't the intent, I've changed it to wrap_content.

2022-02-05 11:30 UTC, Lucas-Fresko commented on app/src/main/res/layout/activity_login.xml
> +      android:layout_height="48dp"
Commit pushed.

2022-02-05 11:39 UTC, Lucas-Fresko commented
Is the margin supposed to be applied to header layout? Or would it be better if it applies to text view? I seem to remember mention of a white band during the meeting as the purpose but that doesn't strike me as conventional for a header.

2022-02-07 07:10 UTC, taurelas commented
> Is the margin supposed to be applied to header layout? Or would it be better if it applies to text view? I seem to remember mention of a white band during the meeting as the purpose but that doesn't strike me as conventional for a header.

Personally I thought by the "header" we meant a text. You added a background and it became a sort of a toolbar but not directly on top of the screen. I would just leave it as it is for now - the AC's are met and we have a screen that clearly shows it's for login

Normally we should have designs ready which make things clearer.

2022-02-07 07:11 UTC, taurelas requested changes

2022-02-07 07:11 UTC, taurelas commented on app/src/main/res/values/dimens.xml
> +    <dimen name="header_height_dimension">48dp</dimen>
let's change it to "header_height", the word dimension is redundant

2022-02-07 07:11 UTC, taurelas commented on app/src/main/res/values/dimens.xml
> +    <dimen name="header_margin_top_dimension">24dp</dimen>
again, let's remove the "dimension"

2022-02-07 10:26 UTC, taurelas approved these changes
Well done!

2022-02-07 13:53 UTC, merged