P2022 1560 implement video player screen layout
intive/patronage22_poznan_mobile pull request #42
Opened 2022-03-13 21:37 UTC by Anna-Surma

Implements Video Player screen according to design 
Clicking on "X" goes back to movie details
Video Player screen opens in a new Activity which is in horizontal orientation

2022-03-14 13:06 UTC, Lucas-Fresko requested changes

2022-03-16 12:01 UTC, kosiara commented on app/src/main/res/layout/activity_video_player.xml
> +            android:id="@+id/close_video"
I'm not we need that. Variables have types...

val closeVideoImage: ImageView = view.findViewById(R.id. close_video)

2022-03-16 12:04 UTC, kosiara commented
![Screenshot 2022-03-16 at 13 03 29](https://user-images.githubusercontent.com/4531522/158585990-fcfb366d-1b6b-4129-ba34-31b49fbb20b4.png)

Does your branch need a rebase? 
There are changes outside of this PR here..

2022-03-17 19:29 UTC, taurelas approved these changes

2022-03-17 19:29 UTC, Lucas-Fresko approved these changes

2022-03-17 19:34 UTC, merged