P2022-701 Login Form
intive/patronage22_poznan_mobile pull request #5
Opened 2022-02-08 14:19 UTC by Anna-Surma

Adds two EditText fields - login and password with description. 
Adds one log in button. The button only exists.

2022-02-08 16:03 UTC, Lucas-Fresko commented on app/src/main/res/layout/activity_login.xml
> +      android:id="@+id/linearLayout"
I suggest changing the id to make it clear what it refers to.

Question for our glorious leaders: What naming convention shall we use for id's?

2022-02-08 16:33 UTC, Lucas-Fresko approved these changes
PR is functional.

Adrian is awaiting a merge to implement validation.

2022-02-08 16:46 UTC, taurelas commented on app/src/main/res/layout/activity_login.xml
> +      android:id="@+id/linearLayout"
it's a good question, we can have a short meeting about this. However, regardless of the outcome this is not the best name - we can name it `form` or `form_layout` or `formLayout`

2022-02-08 16:56 UTC, taurelas requested changes

2022-02-08 16:56 UTC, taurelas commented on app/src/main/res/layout/activity_login.xml
> +      android:layout_marginTop="@dimen/loginEditText_marginTop"
good work on using dimens 👍🏼

2022-02-08 16:56 UTC, taurelas commented on app/src/main/res/values/dimens.xml
> +    <dimen name="passwordEditText_marginHorizontal">@dimen/loginEditText_marginHorizontal</dimen>
@Anna-Surma you need to change the name to reflect what it does now, it's going to be for both edittexts

2022-02-08 17:08 UTC, Lucas-Fresko commented on app/src/main/res/layout/activity_login.xml
> +      android:id="@+id/linearLayout"
It's the header layout I added earlier, ID was needed here for constraint layout parameters so this will be `header_layout` or such.

2022-02-08 17:34 UTC, taurelas commented on app/src/main/res/layout/activity_login.xml
> +      android:id="@+id/linearLayout"
ok, perfect

2022-02-09 02:55 UTC, taurelas approved these changes

2022-02-09 11:53 UTC, merged