P2022-702 Login form validation
intive/patronage22_poznan_mobile pull request #6
Opened 2022-02-09 11:44 UTC by AdrianPat

2022-02-09 12:39 UTC, kosiara reviewed
Adrian, you have to delete Anna's commits from your PR :)

2022-02-09 16:18 UTC, Lucas-Fresko approved these changes

2022-02-09 16:18 UTC, Lucas-Fresko commented on app/src/main/java/com/intive/patronage22/intivi/LoginActivity.kt
> +                return isLoginOK && isPasswordOK
Are these booleans useful? I imagine they might be in the future, but it adds to the clutter if we never use them.

2022-02-09 16:18 UTC, Lucas-Fresko commented on app/src/main/java/com/intive/patronage22/intivi/LoginActivity.kt
> +            loginValidation()
Question for leaders; Is it a good idea and standard to always put things like these in separate functions (even if it gets called from the very next line?), or is it ok to just leave it inside of setOnClickListener?

Also, how to comment on several lines of code?

2022-02-09 16:28 UTC, AdrianPat commented on app/src/main/java/com/intive/patronage22/intivi/LoginActivity.kt
> +                return isLoginOK && isPasswordOK
They might be useful for navigation to the Home (Home Screen).

2022-02-10 17:05 UTC, taurelas requested changes

2022-02-10 17:05 UTC, taurelas commented on app/src/main/java/com/intive/patronage22/intivi/LoginActivity.kt
> +            loginValidation()
You comment several lines of code like this:
```
/* this is a
very long text
that has several lines */
```

2022-02-14 08:04 UTC, taurelas requested changes

2022-02-14 08:04 UTC, taurelas commented on app/src/main/java/com/intive/patronage22/intivi/LoginActivity.kt
> +            findViewById<EditText>(R.id.loginEditText).error = ""
you can store the `(findViewById<EditText>(R.id.loginEditText)` in a variable:
val editText = (findViewById<EditText>(R.id.loginEditText)

1. Previously you had it at the class level but it was unnecessary because only this logic here used it
2. But now you completely removed it which is not good either. `findViewById` method is expensive - it checks every view in the layout if it has the id. Once you do find it, it's better to keep it somewhere:
`val editText = findViewById<EditText>(R.id.loginEditText).`

So now you will have the benefit of referring to the variable : editText.text or editText.error but the variable scope is limited to the isLoginOk function. Once the function is complete, the variable will be destroyed

Also, if you do a similar thing in `isPasswordOK()`, you can name the variable editText again, because the code in that method does not see the other `editText`

2022-02-14 15:36 UTC, taurelas approved these changes

2022-02-14 15:36 UTC, taurelas commented on app/src/main/java/com/intive/patronage22/intivi/LoginActivity.kt
> +        val editText = findViewById<EditText>(R.id.loginEditText)
ok, for information only because this would simply make it more readable but in Kotlin you could also write it like this:
with(findViewById<EditText>(R.id.loginEditText) {
  if(text.isEmpty() {
    error = ""
  }
}

You can read more about it here https://kotlinlang.org/docs/scope-functions.html

2022-02-14 18:47 UTC, merged