P2022-2071 Separete GridData
intive/patronage22_poznan_mobile pull request #66
Opened 2022-03-30 16:22 UTC by Bombozaur666

Create data class for movie item
create movie list
add bind to home fragment

2022-03-31 17:51 UTC, taurelas requested changes

2022-03-31 17:51 UTC, taurelas commented on app/src/main/java/com/intive/patronage22/intivi/model/MovieItem.kt
> +var movieList = arrayListOf<MovieItem>()
this needs to be moved somewhere

2022-03-31 17:51 UTC, taurelas commented on app/src/main/java/com/intive/patronage22/intivi/model/MovieItem.kt
> +class MovieItem(
we could use data class here

2022-03-31 17:51 UTC, taurelas commented on app/src/main/java/com/intive/patronage22/intivi/model/MovieItem.kt
> +var movieList = arrayListOf<MovieItem>()
best to move it to a viewmodel

2022-03-31 18:06 UTC, taurelas requested changes
please change

2022-04-04 17:06 UTC, kosiara commented on app/src/main/java/com/intive/patronage22/intivi/model/MovieItem.kt
> +class MovieItem(
ok

2022-04-04 17:06 UTC, merged