P2022 703
intive/patronage22_poznan_mobile pull request #9
Opened 2022-02-09 20:48 UTC by PienkowskaMarta

Adds navigation from login form to home screen.

2022-02-10 08:59 UTC, Lucas-Fresko reviewed
Here's a link explaining the .idea folder: https://betterprogramming.pub/exploring-the-idea-folder-790931c19191

The deploymentTargetDropDown.xml stores your emulator target device, which I'm guessing we don't need in the remote repository.

The codeStyles are apparently a good idea to have, but if we decide to implement it on remote, it should probably have its own task and PR.

2022-02-10 16:37 UTC, taurelas requested changes
please reset the branch to master and commit only final changes from the LoginActivity as advised on Slack

2022-02-10 20:19 UTC, Lucas-Fresko approved these changes
Nicely done!

2022-02-11 03:55 UTC, taurelas requested changes

2022-02-11 03:55 UTC, taurelas commented on app/src/main/java/com/intive/patronage22/intivi/LoginActivity.kt
> +        findViewById<Button>(R.id.loginButton).setOnClickListener(listener)
you forgot to copy the imports! :) they are usually collapsed in Android Studio so they're easy to miss.
For the future - It's always a good idea to run the app before the commit and ensure it compiles
Please do so and fix the issues

2022-02-11 08:51 UTC, PienkowskaMarta commented on app/src/main/java/com/intive/patronage22/intivi/LoginActivity.kt
> +        findViewById<Button>(R.id.loginButton).setOnClickListener(listener)
Thanks for noticing that! I have added missing imports. It works now.

2022-02-11 10:48 UTC, AdrianPat commented
There is a shorter way:

```
findViewById<Button>(R.id.loginButton).setOnClickListener {
    startActivity(Intent(applicationContext, MainActivity::class.java))
}
```

It works. What about this code?

2022-02-11 14:44 UTC, Lucas-Fresko commented
Is the reusability intended to come from implementing cases for different id's in the 'when ->' ?

I played around with;
/* private fun goToActivity(activityToGoTo: Class<*>?){
        startActivity(Intent(this, activityToGoTo))
    }
*/

and;
` findViewById<Button>(R.id.loginButton).setOnClickListener{goToActivity(MainActivity::class.java)} `

But I'm not sure if there will ever be a need to go to MainActivity from more than one place so I'd be satisfied with just one line, while your listener can be used more flexibly by calling other functions from it.

2022-02-14 08:05 UTC, taurelas approved these changes

2022-02-14 16:06 UTC, merged